import java.io.IOError;

public class excecoes {
	
	private static final boolean ArithmeticException = false;
	private static final boolean ArrayIndexOutOfBoundsException = false;

	public static void main(String[] args) throws Exception {
		
		int[] num1= {4, 3, 5, 12, 8};
		int[] num2= {4, 2, 0, 6};
		
		for (int i=0; i<num1.length; i++) {
			try {
				if (num1[i] % 2 !=0) {
					throw new Exception("Número ímpar, resultado não exato!");
				}
				if (ArithmeticException ) {
					throw new Exception("Divisão por 0, sem resultados!");
				}
				if (ArrayIndexOutOfBoundsException ) {
					throw new Exception("Conjunto de Arrays incompleto");
				}
		
	} catch (NullPointerException e) {
		System.out.println("Ocorreu um erro!");
}
}
}
}
